package model;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 16 14:44:16 IST 2026
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class siteQBVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        SiteId,
        StudyId,
        EffectiveStartDate,
        EffectiveTodate,
        State,
        SiteNum;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int SITEID = AttributesEnum.SiteId.index();
    public static final int STUDYID = AttributesEnum.StudyId.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVETODATE = AttributesEnum.EffectiveTodate.index();
    public static final int STATE = AttributesEnum.State.index();
    public static final int SITENUM = AttributesEnum.SiteNum.index();

    /**
     * This is the default constructor (do not remove).
     */
    public siteQBVORowImpl() {
    }
}

