package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 16 14:44:17 IST 2026
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class siteQBVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public siteQBVOImpl() {
    }
}

